-- Use During Development
-- DROP DATABASE IF EXISTS toy_tips_db;
-- CREATE DATABASE toy_tips_db;
-- USE toy_tips_db;

-- Use For Production
DROP DATABASE IF EXISTS bi1kvz8znfs4e1vp;
CREATE DATABASE bi1kvz8znfs4e1vp;
USE bi1kvz8znfs4e1vp;

-- Table structure for `reviews`

CREATE TABLE `reviews` (
  `Review_ID` bigint(20) NOT NULL auto_increment,
  `User_ID` bigint(20) default '0',
  `ToyName` varchar(150) default NULL,
  `Accepted` char(1) NOT NULL default 'Z',
  `AgeRange1` varchar(40) default NULL,
  `assigned_id` bigint(20) NOT NULL default '0',
  `categories` text,
  `category` varchar(255) default NULL,
  `CertOfInsurance` char(1) NOT NULL default 'Z',
  `click_count` bigint(20) default NULL,
  `client_type` varchar(255) default NULL,
  `company_name` varchar(100) default NULL,
  `company_address` varchar(100) default NULL,
  `company_address2` varchar(100) default NULL,
  `company_address_city` varchar(100) default NULL,
  `company_address_zipcode` varchar(100) default NULL,
  `company_address_state` varchar(100) default NULL,
  `company_contact` varchar(100) default NULL,
  `company_phone` varchar(100) default NULL,
  `company_email` varchar(100) default NULL,
  `Character_Development` int(11) default NULL,
  `classicnew` tinyint(4) NOT NULL default '0',
  `Classic_Toys` tinyint(4) NOT NULL default '0',
  `client_ip` varchar(15) default NULL,
  `company_website` varchar(150) default NULL,
  `company_fax` varchar(100) default NULL,
  `company_contact_title` varchar(100) default NULL,
  `company_address_country` varchar(100) default NULL,
  `creation_datetime` timestamp NOT NULL default '0000-00-00 00:00:00',
  `durability` varchar(100) default NULL,
  `etip_date` date default NULL,
  `easeofuse` varchar(100) default NULL,
  `fox_date` date default NULL,
  `Flunked` tinyint(4) default '0',
  `image_available` int(11) NOT NULL default '0',
  `image_filepath` varchar(255) default NULL,
  `Kids_Rating` int(11) default NULL,
  `Long_Review` text,
  `Low_Age` varchar(20) default NULL,
  `Low_Price` varchar(20) default NULL,
  `MadeInCountry` varchar(100) NOT NULL default '',
  `manufacturer_id` bigint(20) NOT NULL default '0',
  `mfg_comment` text,
  `mfg_desc` text,
  `mfg_emailsent` tinyint(4) NOT NULL default '0',
  `mfg_emailsent_datetime` datetime default NULL,
  `Minimum_Age` int(11) default NULL,
  `modification_datetime` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `Motor_Movement` int(11) default NULL,
  `price_range` varchar(10) default NULL,
  `product_website` varchar(150) default NULL,
  `publicist_name` varchar(100) default NULL,
  `publish_date` date NOT NULL,
  `publicist_address` varchar(100) default NULL,
  `publicist_address2` varchar(100) default NULL,
  `publicist_address_city` varchar(100) default NULL,
  `publicist_address_state` varchar(100) default NULL,
  `publicist_address_zipcode` varchar(100) default NULL,
  `publicist_phone` varchar(100) default NULL,
  `publicist_email` varchar(100) default NULL,
  `publicist_fax` varchar(100) default NULL,
  `publicist_contact` varchar(100) default NULL,
  `publicist_contact_title` varchar(100) default NULL,
  `publicist_address_country` varchar(100) default NULL,
  `record_category_toys` tinyint(4) NOT NULL default '0',
  `record_category_baby_safety` tinyint(4) NOT NULL default '0',
  `record_category_juvenile_gear` tinyint(4) NOT NULL default '0',
  `record_category_nursery` tinyint(4) NOT NULL default '0',
  `record_category_new_mom` tinyint(4) NOT NULL default '0',
  `record_category_executive` tinyint(4) NOT NULL default '0',
  `record_category_family_videos` tinyint(4) NOT NULL default '0',
  `record_category_family_software` tinyint(4) NOT NULL default '0',
  `record_category_cooking` tinyint(4) NOT NULL default '0',
  `record_category_dad` tinyint(4) default NULL,
  `record_category_cooking_vs` varchar(100) default NULL,
  `record_category_travel` tinyint(4) default '0',
  `record_category_new_mom_category` varchar(100) default NULL,
  `record_category_baby_style` tinyint(4) NOT NULL default '0',
  `record_category_kid_places` tinyint(4) NOT NULL default '0',
  `reviewer_id` bigint(20) NOT NULL default '0',
  `reviewer_comment` text,
  `reviewer_longreview` text,
  `reviewer_boys_num` bigint(20) default NULL,
  `reviewer_boys_agegroup` varchar(50) default NULL,
  `reviewer_girls_num` bigint(20) default NULL,
  `reviewer_girls_agegroup` varchar(50) default NULL,
  `reviewer_rating` int(11) default NULL,
  `reviewer_kidsrating` int(11) default NULL,
  `reviewer_motor` int(11) default NULL,
  `reviewer_thinking` int(11) default NULL,
  `reviewer_character` int(11) default NULL,
  `reviewer_received` tinyint(4) NOT NULL default '0',
  `reviewer_durability` int(11) default NULL,
  `reviewer_social` int(11) default NULL,
  `reviewer_easeofuse` int(11) default NULL,
  `reviewer_Sensibility` int(11) default NULL,
  `reviewer_valuetoconsumer` int(11) default NULL,
  `sensibility` varchar(100) default NULL,
  `Short_Review` text,
  `sku` varchar(50) default NULL,
  `Social_Interaction` int(11) default NULL,
  `status` varchar(100) default 'New',
  `subcat_travel` varchar(255) default NULL,
  `subcat_kidsspaces` varchar(255) default NULL,
  `subcat_expectant` varchar(255) default NULL,
  `subcat_juvenile` varchar(255) default NULL,
  `tip` text,
  `tofriend_count` bigint(20) default NULL,
  `ToyManufacturer` varchar(100) default NULL,
  `ToyTipsRating` int(11) default NULL,
  `Thinking_Skills` int(11) default NULL,
  `ttstatus` varchar(50) default NULL,
  `upload_name` varchar(255) default NULL,
  `upload_size` varchar(20) default NULL,
  `upload_type` varchar(20) default NULL,
  `upload_realname` varchar(255) default NULL,
  `valuetoconsumer` varchar(100) default NULL,
  `web_publish` tinyint(4) NOT NULL default '0',
  `weekly_date` date NOT NULL default '0000-00-00',
  `DEPRECIATEDnew_review` tinyint(4) default NULL,
  `DEPRECIATEDpublish_date` varchar(10) default NULL,
  PRIMARY KEY  (`Review_ID`),
  KEY `User_ID` (`User_ID`),
  KEY `classicnew` (`classicnew`),
  KEY `AgeRange1` (`AgeRange1`),
  KEY `reviewer_id` (`reviewer_id`,`assigned_id`),
  KEY `manufacturer_id` (`manufacturer_id`),
  KEY `assigned_id` (`assigned_id`),
  KEY `record_category_new_mom` (`record_category_new_mom`),
  KEY `web_publish` (`web_publish`),
  KEY `CertOfInsurance` (`CertOfInsurance`),
  KEY `accepted` (`Accepted`),
  KEY `Review_ID` (`Review_ID`),
  FULLTEXT KEY `ToyName` (`ToyName`,`ToyManufacturer`,`Short_Review`,`Long_Review`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1005770;